source 'https://rubygems.org'
gem 'pry', :git => 'git@github.com:pry/pry.git' 
gem 'pry-rescue'
gem 'pry-doc'
#gem 'pry-debugger', :git => 'git@github.com:nixme/pry-debugger.git'
gem 'pry-stack_explorer'
gem 'rspec'
gem 'require_all'
gem 'activesupport-inflector'
gem 'i18n'
